# ---------------------------------------------------------------------------------------------------------------------------------
# Налаштування мережі
# Ці налаштування забезпечують детальний контроль над поведінкою мережі та обробкою пакетів сервера.
# Налаштування цих параметрів може допомогти оптимізувати продуктивність мережі та забезпечити безпечний зв'язок між сервером і клієнтами.
# ---------------------------------------------------------------------------------------------------------------------------------


# ---------------------------------------------------------------------------------------------------------------------------------
# Загальні налаштування мережі
# ---------------------------------------------------------------------------------------------------------------------------------

# Час очікування при вимкненні
# Час у секундах, протягом якого сервер чекає на завершення надсилання/отримання пакетів під час вимкнення.
# За замовчуванням: 5 секунд
ShutdownWaitTime = 5

# Визначає, чи ввімкнено відкидання пакетів.
# За замовчуванням: False
DropPackets = False

# Ліміт для відкидання пакетів
# Визначає ліміт для відкидання пакетів, що можуть бути видалені. Більші значення дозволяють утримувати більше пакетів у черзі
# перед початком відкидання, зменшуючи втрату пакетів, але використовуючи більше пам'яті.
# За замовчуванням: 250
DropPacketThreshold = 250


# ---------------------------------------------------------------------------------------------------------------------------------
# Налаштування ThreadPool
# ---------------------------------------------------------------------------------------------------------------------------------

# Кількість потоків у пулі виконання пакетів.
# Визначає, скільки потоків готові негайно обробляти завдання.
# Якщо встановлено значення 0, буде налаштовано автоматично (кількість ядер процесора x 4).
# Більше потоків обробляють більше завдань одночасно, менше потоків економлять ресурси.
# За замовчуванням: 0 (автоматично налаштовується як доступні ядра x 4)
ThreadPoolSize = 4

# Рівень пріоритету потоків у пулі виконання пакетів.
# Визначає важливість цих потоків щодо інших системних процесів.
# Значення варіюються від 1 (найнижчий пріоритет) до 10 (найвищий пріоритет).
# За замовчуванням: 5 (середній пріоритет, підходить для загального використання)
ThreadPriority = 5


# ---------------------------------------------------------------------------------------------------------------------------------
# Конфігурації пулу буферів
# ---------------------------------------------------------------------------------------------------------------------------------

# Початковий коефіцієнт, розмір і розмір буфера для малих, середніх і великих пулів.
# Ці пули оптимізують використання пам'яті шляхом повторного використання звичайних розмірів буфера.

# Розмір сегмента буфера
# Розмір сегментів для динамічних буферів, що використовуються для збільшення розміру за потреби.
# За замовчуванням: 64
BufferSegmentSize = 64

# Дозволяє пулу буферів автоматично збільшуватися, коли він досягає максимальної ємності.
# За замовчуванням: True
BufferPool.AutoExpandCapacity = True

# Початковий коефіцієнт
# Множник для попередньої ініціалізації пулів буферів. Більший коефіцієнт = більше попередньо створених буферів.
# За замовчуванням: 0 (без попередньої ініціалізації)
BufferPool.InitFactor = 0

# Пул порожніх буферів
# Розмір та кількість буферів для порожніх мережевих пакетів.
# За замовчуванням: 100 буферів по 2 байти кожен.
BufferPool.Empty.Size = 100
BufferPool.Empty.BufferSize = 2

# Мінімальний пул буферів
# Розмір і кількість буферів для мережевих пакетів мінімального розміру.
# За замовчуванням: 100 буферів по 64 байти кожен.
BufferPool.Minimum.Size = 100
BufferPool.Minimum.BufferSize = 64

# Дуже маленький пул буферів
# Розмір та розмір буфера для дуже малих мережевих пакетів.
# За замовчуванням: 75 буферів по 128 байт кожен.
BufferPool.VerySmall.Size = 75
BufferPool.VerySmall.BufferSize = 128

# Малий пул буферів
# Кількість та розмір буфера для малих мережевих пакетів.
# За замовчуванням: 75 буферів по 256 байт кожен.
BufferPool.Small.Size = 75
BufferPool.Small.BufferSize = 256

# Пул малих та великих буферів
# Розмір та розмір буфера для малих та великих мережевих пакетів.
# За замовчуванням: 75 буферів по 512 байт кожен.
BufferPool.LargeSmall.Size = 75
BufferPool.LargeSmall.BufferSize = 512

# Пул буферів середнього-малого розміру
# Розмір та кількість буферів для менших мережевих пакетів середнього розміру.
# За замовчуванням: 50 буферів по 1024 байти кожен.
BufferPool.SmallMedium.Size = 50
BufferPool.SmallMedium.BufferSize = 1024

# Пул буферів середнього розміру
# Розмір та розмір буфера для пакетів середньої мережі.
# За замовчуванням: 50 буферів по 2048 байтів кожен.
BufferPool.Medium.Size = 50
BufferPool.Medium.BufferSize = 2048

# Пул буферів середнього розміру
# Розмір та обсяг буфера для більших середніх мережевих пакетів.
# За замовчуванням: 50 буферів по 4096 байтів кожен.
BufferPool.LargeMedium.Size = 50
BufferPool.LargeMedium.BufferSize = 4096

# Пул великих і малих буферів
# Розмір і розмір буфера для великих і малих мережевих пакетів.
# За замовчуванням: 25 буферів по 8192 байти кожен.
BufferPool.SmallLarge.Size = 25
BufferPool.SmallLarge.BufferSize = 8192

# Пул великих буферів
# Розмір та кількість буферів для великих мережевих пакетів.
# За замовчуванням: 25 буферів по 16384 байти кожен.
BufferPool.Large.Size = 25
BufferPool.Large.BufferSize = 16384

# Дуже великий пул буферів
# Розмір та кількість буферів для дуже великих мережевих пакетів.
# За замовчуванням: 25 буферів по 24576 байт кожен.
BufferPool.VeryLarge.Size = 25
BufferPool.VeryLarge.BufferSize = 24576

# Максимальний пул буферів
# Розмір і кількість буферів для мережевих пакетів максимального розміру.
# За замовчуванням: 10 буферів по 32768 байт кожен.
BufferPool.Maximum.Size = 10
BufferPool.Maximum.BufferSize = 32768
