# ---------------------------------------------------------------------------
# База даних
# ---------------------------------------------------------------------------

# Клас драйвера JDBC для бази даних. 
# За замовчуванням: com.mysql.cj.jdbc.Driver
Driver = com.mysql.cj.jdbc.Driver

# URL підключення до бази даних.
# За замовчуванням: jdbc:mysql://localhost/login?useUnicode=true&characterEncoding=utf-8&useSSL=false&connectTimeout=10000&interactiveClient=true&sessionVariables=wait_timeout=600,interactive_timeout=600&autoReconnect=true
URL = jdbc:mysql://localhost/login?useUnicode=true&characterEncoding=utf-8&useSSL=false&connectTimeout=10000&interactiveClient=true&sessionVariables=wait_timeout=600,interactive_timeout=600&autoReconnect=true

# Користувач бази даних. Стандартним є "root", але це не рекомендовано.
Login = root

# Пароль бази даних. Залиште порожнім, якщо пароля немає.
Password = qsmiim13fv92

# Максимальна кількість одночасних з'єднань з базою даних.
# За замовчуванням: 5
MaximumDatabaseConnections = 5

# Визначає, чи повинні з'єднання з базою даних періодично перевірятися.
# За замовчуванням: False
TestDatabaseConnections = False


# ---------------------------------------------------------------------------
# Автоматичне резервне копіювання бази даних
# ---------------------------------------------------------------------------
# Створює резервні копії бази даних, коли сервер перезавантажується або вимикається.
BackupDatabase = True

# Шлях до папки bin MySQL. Потрібно лише в Windows.
MySqlBinLocation = C:\Program Files\MySQL\MySQL Server 8.4\bin

# Шлях, де зберігаються резервні копії бази даних.
BackupPath = ../backup/

# Максимальна кількість днів для зберігання резервних копій.
# Старі файли в папці резервних копій будуть видалені.
# Встановіть 0, щоб вимкнути.
BackupDays = 30
